// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentRestAPI.Models;

#nullable disable

namespace StudentRestAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentRestAPI.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            DepartmentID = 1,
                            Email = "john@john.com",
                            FirstName = "John",
                            Gender = 0,
                            LastName = "Doe",
                            PhotoPath = "https://upload.wikimedia.org/wikipedia/commons/b/bc/Unknown_person.jpg"
                        },
                        new
                        {
                            StudentID = 2,
                            DepartmentID = 2,
                            Email = "alex@alex.com",
                            FirstName = "Alex",
                            Gender = 0,
                            LastName = "John",
                            PhotoPath = "https://upload.wikimedia.org/wikipedia/commons/b/bc/Unknown_person.jpg"
                        },
                        new
                        {
                            StudentID = 3,
                            DepartmentID = 3,
                            Email = "emily@emily.com",
                            FirstName = "Emily",
                            Gender = 1,
                            LastName = "Doe",
                            PhotoPath = "https://upload.wikimedia.org/wikipedia/commons/b/bc/Unknown_person.jpg"
                        },
                        new
                        {
                            StudentID = 4,
                            DepartmentID = 4,
                            Email = "lizzy@lizzy.com",
                            FirstName = "Lizzy",
                            Gender = 1,
                            LastName = "Addrison",
                            PhotoPath = "https://upload.wikimedia.org/wikipedia/commons/b/bc/Unknown_person.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
